### ISSUE TITLE
TypeError: undefined is not an object (evaluating '$el[0].getBoundingClientRect')

### ISSUE THREAD

**Issue by baldiri** [kartik-v/bootstrap-popover-x#34]
Hi Kartik,

let me show you a column of a grid in my code ant tell when i get the error:

As you see is an EditableColumn with an INPUT_TIME ("kartik-v/yii2-widget-timepicker": "*")

```
[
     'class' => 'kartik\grid\EditableColumn',
     'hAlign' => 'center',
     'options' => ['style' => ['width' => '10%']],
     'attribute' => 'charging_time',
     'value' => function($model) {
                            return Yii::$app->formatter->asTime($model->charging_time);
     },
     'readonly' => function() {
          return (!in_array(Yii::$app->user->identity->role->id, [1, 3, 4]));
     },
     'refreshGrid' => true,
     'editableOptions'=> [
              'inputType' => \kartik\editable\Editable::INPUT_TIME,
              'formOptions'=>['action' => ['/travels/change-charging-time']],
              'asPopover' => true,
               'options'=> [
                     'pluginOptions' => [
                          'showMeridian' => false,
                           'showSeconds' => false,
                     ]
               ]
      ],
],
```
I get error every time that a pjax reload is done. So if i edit inline this o others columns, if i order by any column, if i apply any filter to grid, always after pjax reload grid i get this error. 

Something is not ok when you have timepicker in your grid, and reload grid through pjax.

Debbuger (safari, but i test with chrome and same problem) says:

TypeError: undefined is not an object (evaluating '$el[0].getBoundingClientRect')
getPosition - bootstrap-popover-x.js: line 222

![captura de pantalla 2018-02-12 a les 12 08 10](https://user-images.githubusercontent.com/10255019/36094824-fca76328-0fef-11e8-845c-7fd269c57770.png)

Thanks a lot in advance!

**Comment by joanlopez** [comment]
Dear @kartik-v,

I'm also suffering this issue.

As far as I could debug, the problem is not exactly at the given line ``` bootstrap-popover-x.js: line 222```.
There is an error, true, but it's also present when using ```yii2-widget-datepicker```.

However, the ```datepicker``` can be used despite the error meanwhile the ```timepicker``` not.
So, probably there are two errors to fix.

This problem mentioned in this issue appears after the grid refresh process once the submit succeeded. I've seen that when you open again the editable popover (after a sucessful submit), the ```PopoverX``` constructor is being called again for ```datepicker``` but not for ```timepicker```. 
Nonetheless I'm not sure if the real problem is due to the missing constructor call. 

If you think I can provide more relevant info, don't hesitate to ask me! =)

Thanks a lot for your patience and I hope the information helps you!

**Comment by funkycram** [comment]
Same problem here (my page is loaded with pjax) :
```
$el[0] is undefined
```
Thanks
