### ISSUE TITLE
Not able to make it work for dynamic markup generation scenario

### ISSUE THREAD

**Issue by sguddati** [kartik-v/bootstrap-popover-x#4]
Hello,

$('[data-toggle="popover-x"]') is registered with click and keyup functions as part of document ready event. But in the scenarios where the html mark up is dynamically generated (I am using handlebars as template engine to generate the markup), this design is not working. Any suggestions?

Can we provide these registration methods as seperate methods that we can call after HTML Mark up is attached to the dom objects?

Srinivas.

**Comment by AndreSilva1993** [comment]
So, I'm using this gridview with the editable column and all works well. However when the data is dynamically changed (pagination for instance), the popovers stop appearing. I googled and found that I had to bind the popover the new elements that were added to DOM so I created this function.

$('body').on('click', "[data-toggle='popover-x']", function(e) {
    var target = $(e.target).data('target');
    var options = {
        "backdrop": "true",
        "keyboard": "true",
        "show": "true"
    };
    $(target).popoverX(options);
});

This doesn't seem to work, since after dynamically changing the page and clicking the editable button this method is triggered the popover still doesn't appear. What am I doing wrong?
